name: Daily Twitter Post

on:
  schedule:
    - cron: "0 2 * * *"   # 09:00 WIB window start (02:00 UTC)
    - cron: "0 11 * * *"  # 18:00 WIB window start (11:00 UTC)
  workflow_dispatch: {}  # manual run button

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install tweepy

      - name: Random delay before posting
        run: |
          # Random sleep between 0 and 5 hours (0–18000 seconds)
          sleep $(( RANDOM % 18000 ))

      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: python "postt.py"
